

/*import { GoogleSpreadsheet } from 'https://cdn.jsdelivr.net/npm/google-spreadsheet@3.1.15/dist/esm/index.mjs';
import { JWT } from 'https://cdn.jsdelivr.net/npm/google-auth-library@6.2.0/build/src/auth/jwtclient.mjs';
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: "brewandbuzz-889@smoke-test-383702.iam.gserviceaccount.com",
  key: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC2TSHpEHTaPA5Y\nzIEEjQPKAyNrwsPQrjqhsoTGkN2fUd4D3bZj0oS3+NNJ/3s2m0qF/u+BPQaFZ+Eq\nW5Hy+sYHQXSJYUsUM6YTASQOgz1ocOFkaGICc1OHsoHEK8JHVTxwvj8fdX0752+L\ngxLT1IbVu3XNjjnM8DU5D8gMQydVa1qLvwHIAvfn+hV3sJtz3tpA1ZQ0pJYWuzDc\npE3OLUKMduRCPuTAxDW1NgK5lJ801Z+4hWVgfL+rcnDCvzmiIr18a0w9XSOxcu7H\n6BXev+86LCnzJqNN2j1GmLi+RJfa9+tYg4yfa/KXfBDUvgOWL2cDzBMkKxklMlcd\nZS04Vd/7AgMBAAECggEAA1eXqw+vrL6UHsGlDeHN83qqQBQChgVjsso0j/Vg8sZL\n9TMv4FWgNEU+Dmm+Jwqiy6EYX/yv7WsxoBasrtE1JzXmfoxHlZe60Ddho1h5nDwR\njccyIMxfeCnoIiIRPkCMSp7aRmffg2UjUOH2yuZnEG0O5FVaruyqdSDacIscof69\nYURUozBVg0zTPpC/BIqrAqU1yEJp3bzE1CmtIbNfYzljSBsMYdKP+9IgLDS+8GFg\nit7A4cMlBppHAFlzQQHegecCVU84Qw2ncePFqOjloaMxxxPV3/n4cl1CSxwnPTQ4\ngqqA/8EhR8xbQfLxjelADtoiMU7cy6CIHum8zDMcsQKBgQDylVkECgf5/8jwxTuY\nWwsW4V2me7TlqKZKX6cJE8po/SMjN34ImjqygslLJWEXZyTGWASwWWaHiHwbcvLn\ndeLF9Ia1g1S+tObojA13C2RKqF1UD6aqdVUPCz1haTsigrqaBveUlXgrgPK3RmRo\nDpLdXFKTi8KqA2deXszEBaqWiwKBgQDAYkWgGFOw9hNpOLD5BYFLkAAzS5dYnT9J\nXara923N0hCjAD4lXdcA7m7ZYsl/rhbstqAUsQCIFy3QpobW0OynkqY3avlAYygY\np56hqcw9cBLtsbmCojiZcJRo1ON1RMCgtcqulQ65Jb3b41ImRG4zxDKk5P5pRl7k\n1aME9pp6UQKBgGnFApYHRakUhOmuJajtcW1dgDbZ02sbWL4u7KbBkUyrqsltJa/c\nh2FUMy5nsujAWUF+GTVHFbRcpzhUq2KOfP0w/Bdilu279L5KaoiQV/9RX7gKRvIl\nzJuNnArAFj+a3n/QL90COu5FAA83Swov6ItJ+NtKYes9JrH4BbImglW3AoGASfQ9\nAZr4aRlfQt6ZIVEdb9euTAmt51GjZ2eLa1scKberz40jVqfpI6GEmSphfSSGCX72\nsJ2OL8KBSSkKwn9TyeMU5E7J/Bdh7YBZ+ZlVOvTfQeJFBtOnYEynsFjOC2Ffjyfy\n/wOrwj6g6mtLRAygNGQid8LTjdKQXfVGEn1dytECgYBq/vSNKmL5PkJ1NwNPH3Vf\neEk49eAHHVIeNYQKK+9aEcZ819n4iA3reIE+wH9CUshcZyd5+eY9zFZCWOKykc7N\nMqrkEvec/djy7KqqbT01zZ2Gl7Sz+WIX/SRr1gmB/XZJK8R4PBz/B8AxjojnmLaT\n7l9F4L/2/xSxhWkZml3t6w==\n-----END PRIVATE KEY-----\n",
  scopes: [
    'https://www.googleapis.com/auth/spreadsheets',
  ],
});
async function newfunc(){
const doc = new GoogleSpreadsheet('1vQaLvC0EDAyBycOWDiao0NiYxUabxFa0xj6yiZFmJLA', serviceAccountAuth);

await doc.loadInfo(); // loads document properties and worksheets
await doc.updateProperties({ title: 'renamed doc' });



const sheet = await doc.addSheet({ headerValues: ['name', 'email'] });

// append rows
const larryRow = await sheet.addRow(['new','new23@gmail.com']);}
newfunc();*/

// Call the function to add rows to the spreadsheet
// Function to authenticate and add rows to a Google Spreadsheet
/*async function addRowsToSpreadsheet() {
    // Service account credentials
    const serviceAccount = {
      client_email: 'brewandbuzz-889@smoke-test-383702.iam.gserviceaccount.com',
      private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC2TSHpEHTaPA5Y\nzIEEjQPKAyNrwsPQrjqhsoTGkN2fUd4D3bZj0oS3+NNJ/3s2m0qF/u+BPQaFZ+Eq\nW5Hy+sYHQXSJYUsUM6YTASQOgz1ocOFkaGICc1OHsoHEK8JHVTxwvj8fdX0752+L\ngxLT1IbVu3XNjjnM8DU5D8gMQydVa1qLvwHIAvfn+hV3sJtz3tpA1ZQ0pJYWuzDc\npE3OLUKMduRCPuTAxDW1NgK5lJ801Z+4hWVgfL+rcnDCvzmiIr18a0w9XSOxcu7H\n6BXev+86LCnzJqNN2j1GmLi+RJfa9+tYg4yfa/KXfBDUvgOWL2cDzBMkKxklMlcd\nZS04Vd/7AgMBAAECggEAA1eXqw+vrL6UHsGlDeHN83qqQBQChgVjsso0j/Vg8sZL\n9TMv4FWgNEU+Dmm+Jwqiy6EYX/yv7WsxoBasrtE1JzXmfoxHlZe60Ddho1h5nDwR\njccyIMxfeCnoIiIRPkCMSp7aRmffg2UjUOH2yuZnEG0O5FVaruyqdSDacIscof69\nYURUozBVg0zTPpC/BIqrAqU1yEJp3bzE1CmtIbNfYzljSBsMYdKP+9IgLDS+8GFg\nit7A4cMlBppHAFlzQQHegecCVU84Qw2ncePFqOjloaMxxxPV3/n4cl1CSxwnPTQ4\ngqqA/8EhR8xbQfLxjelADtoiMU7cy6CIHum8zDMcsQKBgQDylVkECgf5/8jwxTuY\nWwsW4V2me7TlqKZKX6cJE8po/SMjN34ImjqygslLJWEXZyTGWASwWWaHiHwbcvLn\ndeLF9Ia1g1S+tObojA13C2RKqF1UD6aqdVUPCz1haTsigrqaBveUlXgrgPK3RmRo\nDpLdXFKTi8KqA2deXszEBaqWiwKBgQDAYkWgGFOw9hNpOLD5BYFLkAAzS5dYnT9J\nXara923N0hCjAD4lXdcA7m7ZYsl/rhbstqAUsQCIFy3QpobW0OynkqY3avlAYygY\np56hqcw9cBLtsbmCojiZcJRo1ON1RMCgtcqulQ65Jb3b41ImRG4zxDKk5P5pRl7k\n1aME9pp6UQKBgGnFApYHRakUhOmuJajtcW1dgDbZ02sbWL4u7KbBkUyrqsltJa/c\nh2FUMy5nsujAWUF+GTVHFbRcpzhUq2KOfP0w/Bdilu279L5KaoiQV/9RX7gKRvIl\nzJuNnArAFj+a3n/QL90COu5FAA83Swov6ItJ+NtKYes9JrH4BbImglW3AoGASfQ9\nAZr4aRlfQt6ZIVEdb9euTAmt51GjZ2eLa1scKberz40jVqfpI6GEmSphfSSGCX72\nsJ2OL8KBSSkKwn9TyeMU5E7J/Bdh7YBZ+ZlVOvTfQeJFBtOnYEynsFjOC2Ffjyfy\n/wOrwj6g6mtLRAygNGQid8LTjdKQXfVGEn1dytECgYBq/vSNKmL5PkJ1NwNPH3Vf\neEk49eAHHVIeNYQKK+9aEcZ819n4iA3reIE+wH9CUshcZyd5+eY9zFZCWOKykc7N\nMqrkEvec/djy7KqqbT01zZ2Gl7Sz+WIX/SRr1gmB/XZJK8R4PBz/B8AxjojnmLaT\n7l9F4L/2/xSxhWkZml3t6w==\n-----END PRIVATE KEY-----\n",

    };

    // Load the Google Spreadsheet API
    await gapi.client.load('https://content.googleapis.com/discovery/v1/apis/sheets/v4/rest');

    // Authorize using the service account credentials
    await gapi.auth.authorize({
      'client_email': serviceAccount.client_email,
      'signingKey': serviceAccount.private_key,
      'scope': 'https://www.googleapis.com/auth/spreadsheets',
    });

    // Create a new Google Spreadsheet instance
    const doc = new gapi.client.sheets.SpreadsheetsResource();

    // Load the spreadsheet by its ID
    const spreadsheetId = '1vQaLvC0EDAyBycOWDiao0NiYxUabxFa0xj6yiZFmJLA';
    const response = await doc.get({
      spreadsheetId: spreadsheetId,
    });

    // Get the first sheet from the spreadsheet
    const sheet = response.result.sheets[0];

    // Set the title of the spreadsheet
    const updateResponse = await doc.batchUpdate({
      spreadsheetId: spreadsheetId,
      requests: [{
        updateSpreadsheetProperties: {
          properties: { title: 'renamed doc23' },
          fields: 'title',
        },
      }],
    });

    // Add a new sheet with headers "name" and "email"
    const addSheetResponse = await doc.batchUpdate({
      spreadsheetId: spreadsheetId,
      requests: [{
        addSheet: {
          properties: {
            title: 'New Sheet',
            gridProperties: {
              rowCount: 1,
              columnCount: 2,
            },
            headerRowValues: ['name', 'email'],
          },
        },
      }],
    });

    // Append a row to the new sheet
    const appendResponse = await doc.values.append({
      spreadsheetId: spreadsheetId,
      range: 'New Sheet',
      valueInputOption: 'USER_ENTERED',
      resource: {
        values: [['new', 'new@gmail.com']],
      },
    });

    console.log('Rows added successfully!');
  }

  // Load the Google API client library
  function handleClientLoad() {
    gapi.load('client', initClient);
  }

  // Initialize the Google API client
  function initClient() {
    gapi.client.init({
      apiKey: 'YOUR_API_KEY',
      discoveryDocs: ['https://sheets.googleapis.com/$discovery/rest?version=v4'],
    }).then(() => {
      // Call the function to add rows to the spreadsheet
      addRowsToSpreadsheet();
    });}*/
// if creating a new sheet, you can set the header row

var slider = document.getElementById("myRange-one");

var slider_two = document.getElementById("myRange-two");

var slider_three = document.getElementById("myRange-three");

var slider_four = document.getElementById("myRange-four");
var slider_five = document.getElementById("myRange-five");

var output = document.getElementById("demo");

var output_two = document.getElementById("demo-two");
var output_three = document.getElementById("demo-three");
var output_four = document.getElementById("demo-four");
var output_five = document.getElementById("demo-five");
output.innerHTML = slider.value+" Qty";

output_two.innerHTML = slider_two.value+" Qty";
output_three.innerHTML = slider_three.value+" Qty";
output_four.innerHTML = slider_four.value+" Qty";
output_five.innerHTML = slider_five.value+" Qty";
calculator_1=document.getElementById("Calculator-1")

calculator_2=document.getElementById("Calculator-2")
calculator_3=document.getElementById("Calculator-three")
submit_btn = document.getElementById("submit").addEventListener("click",()=>{
calculation_3 =  calc3.innerHTML;
calc3_value = calculation_3.split(" ")[1];

calculation_2 =  calc2.innerHTML;
calc2_value = calculation_2.split(" ")[1]
calculation_1 =  calc.innerHTML;
calc_value = calculation_1.split(" ")[1]
sum = parseInt(calc_value)+parseInt(calc2_value)+parseInt(calc3_value);
console.log(sum.toString)
console.log(`"  ${sum.toString()}"`)
packageObj ={}
var packages = Array.from(document.getElementsByClassName("package"))
console.log(packages)
for(i=0;i<packages.length;i++){
  var standard_package = packages[i].innerHTML.split(":")[0]
  console.log(standard_package)
  packageObj[
    standard_package
  ]=packages[i].innerText.split(':')[1]
}
packages["Total"] = `"  ${sum.toString()}"`;
jsonObj = {}
var p_tags = Array.from(document.getElementsByClassName("wrapper-one"))
for(i=0;i<p_tags.length;i++){
  var service_name = p_tags[i].innerText.split(":")[0]
  jsonObj[
    service_name
  ]=p_tags[i].innerText.split(':')[1]
}

jsonObj['Total']= `  ${sum.toString()} Qty`;
console.log(jsonObj)
console.log(packageObj)
const xhr = new XMLHttpRequest();
  xhr.open("POST", "http://localhost:3000/path/to/server", true);
  xhr.setRequestHeader("Content-Type", "application/json");

  // Convert the data object to JSON and send it to the server
  xhr.send(JSON.stringify(jsonObj));


/*
const xhr1 = new XMLHttpRequest();
  xhr.open("POST", "http://localhost:3000/path/to/server", true);
  xhr.setRequestHeader("Content-Type", "application/json");

  // Convert the data object to JSON and send it to the server
  xhr.send(JSON.stringify(packageObj));

*/
});

form_data = document.getElementById("myForm").addEventListener("submit", function(event) {
    event.preventDefault(); // Prevent the form from submitting normally
// Get the form data
    var formData = new FormData(this);
    const xhr1 = new XMLHttpRequest();
    xhr1.open("POST", "http://localhost:3000/submit-form", true);
    xhr1.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    console.log(formData)
    // Convert the data object to JSON and send it to the server
    xhr1.send(new URLSearchParams(formData));
  
  
  /*
  const xhr1 = new XMLHttpRequest();
    xhr.open("POST", "http://localhost:3000/path/to/server", true);
    xhr.setRequestHeader("Content-Type", "application/json");
  
    // Convert the data object to JSON and send it to the server
    xhr.send(JSON.stringify(packageObj));
  
  */
  });
let calc_btn = document.getElementById("calc-btn-1").addEventListener("click",()=>{
calculator_1.style.display='block';
calculator_2.style.display='none';
calculator_3.style.display='none'

})

let calc_btn_2 = document.getElementById("calc-btn-2").addEventListener("click",()=>{
calculator_1.style.display='none';
calculator_2.style.display='block';
calculator_3.style.display='none'

})

let calc_btn_3 = document.getElementById("calc-btn-3").addEventListener("click",()=>{
calculator_1.style.display='none';
calculator_2.style.display='none';
calculator_3.style.display='block'

})
slider_two.oninput = function() {
output_two.innerHTML =this.value+" Qty";
calc.innerHTML ="&#x20B9; "+   (this.value*99 + slider.oninput()+ slider_three.value*199+slider_four.value*399+slider_five.value*499);
}
slider_three.oninput = function() {
output_three.innerHTML = this.value+" Qty";
calc.innerHTML ="&#x20B9; "+   (this.value*199 + slider_two.value*99 + slider_four.value*399 + slider_five.value*499 + slider.value*49);
}
slider_four.oninput = function() {
output_four.innerHTML =this.value+" Qty";
calc.innerHTML ="&#x20B9; "+   (this.value*399 + slider_three.value*199 + slider_two.value*99 + slider_five.value*499 + slider.value*49);
}
slider_five.oninput = function() {
output_five.innerHTML =this.value+" Qty";
calc.innerHTML ="&#x20B9; "+   (this.value*499 + slider_three.value*199 + slider_four.value*399 + slider_two.value*99 + slider.value*49);
}
slider.oninput = function() {
output.innerHTML =this.value+" Qty";
calc.innerHTML ="&#x20B9; " +(this.value*49+ slider_five.value*499 + slider_three.value*199 + slider_four.value*399 + slider_two.value*99);

return this.value*49;
}
calc = document.getElementById("calc");
calc.innerHTML = "&#x20B9; "+"0";
let dict = {
"Creatives":499,
"Cover Image":399,
"Profile Picture":99,
"Instagram highlights":49,
"Email Banner":199
}
/*
let first_slider = document.getElementById("myRange-three");
output_three =  document.getElementById("demo-three");
output_three.innerHTML= "&#x20B9; "+ "49";
service = document.getElementById("services")
service.innerHTML = "Instagram Highlights";
first_slider.oninput =function() {

switch(this.value){
  case "1":
    service.innerHTML = "Instagram Highlights"
    output_three.innerHTML= "&#x20B9; " + dict["Instagram highlights"]
    calc.innerHTML="&#x20B9; "+ slider.value*49+;
    break;
  case "2":
    service.innerHTML="Profile Picture"
    output_three.innerHTML="&#x20B9; "+ dict["Profile Picture"]
    calc.innerHTML="&#x20B9; "+ slider.value*99;
    break;
  case "3":
    service.innerHTML="Email Banner"
    output_three.innerHTML="&#x20B9; "+ dict["Email Banner"]
    calc.innerHTML="&#x20B9; "+ slider.value*199;
    break;
  case "4":
    service.innerHTML = "Cover Image"
    output_three.innerHTML="&#x20B9; "+ dict["Cover Image"]
    calc.innerHTML="&#x20B9; "+ slider.value*399;
    break;
  case "5":
    service.innerHTML="Creatives"
    output_three.innerHTML="&#x20B9; "+ dict["Creatives"]
    calc.innerHTML= "&#x20B9; "+ slider.value*499;
    break;
  }
}




*/



//calculator 2
var calc2_slider = document.getElementById("calc2-myRange-one");

var calc2_output = document.getElementById("calc2-demo");
//second

var calc2_slider_2 = document.getElementById("calc2-myRange-2");

var calc2_output_2 = document.getElementById("calc2-demo-2");
//third
var calc2_slider_3 = document.getElementById("calc2-myRange-3");

var calc2_output_3 = document.getElementById("calc2-demo-3");

var first_calc = document.getElementById("first-calc");

var second_calc = document.getElementById("second-calc");
var third_calc = document.getElementById("third-calc");
calc2_output.innerHTML = calc2_slider.value+" Qty";

calc2_output_2.innerHTML = calc2_slider_2.value+" Qty";

calc2_output_3.innerHTML = calc2_slider_3.value+" Qty";


var calc2_slider_two = document.getElementById("calc2-myRange-two");
var calc2_output_two = document.getElementById("calc2-demo-two");

calc2_output_two.innerHTML = calc2_slider_two.value+ " second";
var calc2_slider_twoo = document.getElementById("calc2-myRange-twoo");
var calc2_output_twoo = document.getElementById("calc2-demo-twoo");
calc2_output_twoo.innerHTML = calc2_slider_twoo.value+ " second";

var calc2_slider_three = document.getElementById("calc2-myRange-three");
var calc2_output_three = document.getElementById("calc2-demo-three");
calc2_output_three.innerHTML = calc2_slider_three.value+ " second";
//calc2_output_twoo.innerHTML = calc2_slider_two.value+ " second";
calc2 = document.getElementById("calc2");
calc2.innerHTML = "&#x20B9; "+"0";


let calc2_dict = {
"Text and Animated Reels":139,
"Digital Ad animated":99,
"3d Product Video":899
}

//let calc2_first_slider = document.getElementById("calc2-myRange-three");
//calc2_output_three =  document.getElementById("calc2-demo-three");
//calc2_output_three.innerHTML= "&#x20B9; "+ "139";
//calc2_service = document.getElementById("calc2-services")
//calc2_service.innerHTML = "Text and Animated Reels";

calc2_slider_two.oninput = function() {
calc2_output_two.innerHTML = this.value+" seconds";
first_calc.innerHTML = "&#x20B9; "+(this.value*200*calc2_slider.value);
calc2.innerHTML = "&#x20B9; "+(this.value*200*calc2_slider.value+calc2_slider_twoo.value*250*calc2_slider_2.value+ calc2_slider_3.value*1300*calc2_slider_three.value);
return this.value;
}

calc2_slider.oninput = function() {
calc2_output.innerHTML = this.value + " Qty";
first_calc.innerHTML ="&#x20B9; "+( this.value*200*calc2_slider_two.value);
calc2.innerHTML = "&#x20B9; "+(this.value*200*calc2_slider_two.value+calc2_slider_twoo.value*250*calc2_slider_2.value+ calc2_slider_3.value*1300*calc2_slider_three.value);

return this.value*200;
}
// second slider

calc2_slider_twoo.oninput = function() {
calc2_output_twoo.innerHTML = this.value + "seconds";
second_calc.innerHTML = "&#x20B9; "+(this.value*250*calc2_slider_2.value);
calc2.innerHTML = "&#x20B9; "+(this.value*250*calc2_slider_2.value+calc2_slider.value*200*calc2_slider_two.value + calc2_slider_3.value*1300*calc2_slider_three.value);
return this.value*250;
}
calc2_slider_2.oninput = function() {
calc2_output_2.innerHTML = this.value+" Qty";
second_calc.innerHTML = "&#x20B9; "+(this.value*250*calc2_slider_twoo.value);
calc2.innerHTML = "&#x20B9; "+(this.value*250*calc2_slider_twoo.value+calc2_slider.value*200*calc2_slider_two.value+ calc2_slider_3.value*1300*calc2_slider_three.value);
return this.value;
}
// third slider

calc2_slider_3.oninput = function() {
calc2_output_3.innerHTML=this.value+" Qty";
third_calc.innerHTML = "&#x20B9; "+(this.value*1300*calc2_slider_three.value);
calc2.innerHTML = "&#x20B9; "+(this.value*1300*calc2_slider_three.value + calc2_slider_2.value*250*calc2_slider_2.value + calc2_slider.value*200*calc2_slider_two.value);
return this.value*1300;
}
calc2_slider_three.oninput = function() {
calc2_output_three.innerHTML = this.value+" seconds";
third_calc.innerHTML ="&#x20B9; "+ (this.value*1300*calc2_slider_3.value);
calc2.innerHTML =  "&#x20B9; "+(this.value*1300*calc2_slider_3.value + calc2_slider_2.value*250*calc2_slider_2.value + calc2_slider.value*200*calc2_slider_two.value);
return this.value;
}








//Calculator -3

var calc3_slider = document.getElementById("calc3-myRange-one");
var calc3_slider_two = document.getElementById("calc3-myRange-two");
let calc3_slider_three = document.getElementById("calc3-myRange-three");

let calc3_slider_four = document.getElementById("calc3-myRange-four");
calc3_output_three =  document.getElementById("calc3-demo-3");
calc3_output_two = document.getElementById("calc3-demo-two");
calc3_output = document.getElementById("calc3-demo");
calc3_output_four = document.getElementById("calc3-demo-4");


calc3_output.innerHTML = calc3_slider.value+" Qty";


calc3_output_two.innerHTML = calc3_slider_two.value+" Qty";
calc3_output_three.innerHTML = calc3_slider_three.value+" Qty";
calc3_output_four.innerHTML = calc3_slider_four.value+" Qty";




calc3 = document.getElementById("calc3");
calc3.innerHTML = "&#x20B9; "+"0";


let calc3_dict = {
"4k shoot[8hr]":40000,
"4k shoot on croma + edit[8hr]":35000,
"4k shoot on croma + edit(portable)[8hr]":30000,
"At location shoot/reels[4hr]":10000
}

//calc3_service = document.getElementById("calc3-services")
//calc3_service.innerHTML = "4k shoot[8hr]";
/*
calc3_first_slider.oninput =function() {

switch(this.value){
  case "2":
    calc3_service.innerHTML = "4k shoot on croma + edit[8hr]"
    calc3_output_three.innerHTML="&#x20B9; "+  calc3_dict["4k shoot on croma + edit(portable)[8hr]"]
    
  calc3.innerHTML ="&#x20B9; "+ calc2_slider.value*calc2_slider_two.value*30000;
    break;
  case "1":
    calc3_service.innerHTML="4k shoot on croma  "
    calc3_output_three.innerHTML="&#x20B9; "+ calc3_dict["4k shoot on croma + edit[8hr]"]
    calc3.innerHTML ="&#x20B9; "+ calc3_slider.value*calc3_slider_two.value*35000;
    break;
  case "3":
    calc3_service.innerHTML="4k shoot[8hr]"
    calc3_output_three.innerHTML="&#x20B9; "+ calc3_dict["4k shoot[8hr]"]
  calc3.innerHTML ="&#x20B9; "+ calc3_slider.value*calc3_slider_two.value*40000;
    break;
  
  }
  
}
calc3_slider_two.oninput = function() {
output_two.innerHTML = this.value+" Per Second";
console.log(calc3_first_slider.value)
if(calc3_first_slider.value=="1"){
  calc3.innerHTML ="&#x20B9; "+ this.value*(2**calc3_slider.value)*35000;
}
else if(calc3_first_slider.value=="2"){
  calc3.innerHTML="&#x20B9; "+ this.value*calc3_slider.value*30000;

}
else{
  calc3.innerHTML="&#x20B9; "+ this.value*calc3_slider.value*40000;
}
}

calc3_slider.oninput = function() {
calc3_output.innerHTML = this.value+" Qty";
if(calc3_first_slider.value=="1"){
  calc3.innerHTML ="&#x20B9; "+ this.value*calc3_slider_two.value*35000;
}
else if(calc3_first_slider.value=="2"){
  calc3.innerHTML="&#x20B9; "+ this.value*calc3_slider_two.value*30000;

}
else{
  calc3.innerHTML="&#x20B9; "+ this.value*calc3_slider_two.value*40000;
}
}
*/

calc3_slider_two.oninput = function() {
calc3_output_two.innerHTML =this.value+" Qty";
calc3.innerHTML ="&#x20B9; "+   (this.value*10000 + calc3_slider.value*40000+ calc3_slider_three.value*30000+calc3_slider_four.value*30000);
}


calc3_slider_three.oninput = function() {
calc3_output_three.innerHTML = this.value+" Qty";
calc3.innerHTML ="&#x20B9; "+   (this.value*30000 + calc3_slider_two.value*10000 + calc3_slider_four.value*30000 + calc3_slider.value*40000);
}
calc3_slider_four.oninput = function() {
calc3_output_four.innerHTML =this.value+" Qty";
calc3.innerHTML ="&#x20B9; "+   (this.value*30000 + calc3_slider_three.value*30000 + calc3_slider_two.value*10000 +  calc3_slider.value*40000);
}

calc3_slider.oninput = function() {
calc3_output.innerHTML =this.value+" Qty";
calc3.innerHTML ="&#x20B9; " +(this.value*40000+ calc3_slider_three.value*30000 + calc3_slider_four.value*30000 + calc3_slider_two.value*10000);

return this.value*49;
}

console.log(calc3.innerHTML);