const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');


// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: "brewandbuzz-889@smoke-test-383702.iam.gserviceaccount.com",
  key: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC2TSHpEHTaPA5Y\nzIEEjQPKAyNrwsPQrjqhsoTGkN2fUd4D3bZj0oS3+NNJ/3s2m0qF/u+BPQaFZ+Eq\nW5Hy+sYHQXSJYUsUM6YTASQOgz1ocOFkaGICc1OHsoHEK8JHVTxwvj8fdX0752+L\ngxLT1IbVu3XNjjnM8DU5D8gMQydVa1qLvwHIAvfn+hV3sJtz3tpA1ZQ0pJYWuzDc\npE3OLUKMduRCPuTAxDW1NgK5lJ801Z+4hWVgfL+rcnDCvzmiIr18a0w9XSOxcu7H\n6BXev+86LCnzJqNN2j1GmLi+RJfa9+tYg4yfa/KXfBDUvgOWL2cDzBMkKxklMlcd\nZS04Vd/7AgMBAAECggEAA1eXqw+vrL6UHsGlDeHN83qqQBQChgVjsso0j/Vg8sZL\n9TMv4FWgNEU+Dmm+Jwqiy6EYX/yv7WsxoBasrtE1JzXmfoxHlZe60Ddho1h5nDwR\njccyIMxfeCnoIiIRPkCMSp7aRmffg2UjUOH2yuZnEG0O5FVaruyqdSDacIscof69\nYURUozBVg0zTPpC/BIqrAqU1yEJp3bzE1CmtIbNfYzljSBsMYdKP+9IgLDS+8GFg\nit7A4cMlBppHAFlzQQHegecCVU84Qw2ncePFqOjloaMxxxPV3/n4cl1CSxwnPTQ4\ngqqA/8EhR8xbQfLxjelADtoiMU7cy6CIHum8zDMcsQKBgQDylVkECgf5/8jwxTuY\nWwsW4V2me7TlqKZKX6cJE8po/SMjN34ImjqygslLJWEXZyTGWASwWWaHiHwbcvLn\ndeLF9Ia1g1S+tObojA13C2RKqF1UD6aqdVUPCz1haTsigrqaBveUlXgrgPK3RmRo\nDpLdXFKTi8KqA2deXszEBaqWiwKBgQDAYkWgGFOw9hNpOLD5BYFLkAAzS5dYnT9J\nXara923N0hCjAD4lXdcA7m7ZYsl/rhbstqAUsQCIFy3QpobW0OynkqY3avlAYygY\np56hqcw9cBLtsbmCojiZcJRo1ON1RMCgtcqulQ65Jb3b41ImRG4zxDKk5P5pRl7k\n1aME9pp6UQKBgGnFApYHRakUhOmuJajtcW1dgDbZ02sbWL4u7KbBkUyrqsltJa/c\nh2FUMy5nsujAWUF+GTVHFbRcpzhUq2KOfP0w/Bdilu279L5KaoiQV/9RX7gKRvIl\nzJuNnArAFj+a3n/QL90COu5FAA83Swov6ItJ+NtKYes9JrH4BbImglW3AoGASfQ9\nAZr4aRlfQt6ZIVEdb9euTAmt51GjZ2eLa1scKberz40jVqfpI6GEmSphfSSGCX72\nsJ2OL8KBSSkKwn9TyeMU5E7J/Bdh7YBZ+ZlVOvTfQeJFBtOnYEynsFjOC2Ffjyfy\n/wOrwj6g6mtLRAygNGQid8LTjdKQXfVGEn1dytECgYBq/vSNKmL5PkJ1NwNPH3Vf\neEk49eAHHVIeNYQKK+9aEcZ819n4iA3reIE+wH9CUshcZyd5+eY9zFZCWOKykc7N\nMqrkEvec/djy7KqqbT01zZ2Gl7Sz+WIX/SRr1gmB/XZJK8R4PBz/B8AxjojnmLaT\n7l9F4L/2/xSxhWkZml3t6w==\n-----END PRIVATE KEY-----\n",
  scopes: [
    'https://www.googleapis.com/auth/spreadsheets',
  ],
});
async function newfunc(){
const doc = new GoogleSpreadsheet('1vQaLvC0EDAyBycOWDiao0NiYxUabxFa0xj6yiZFmJLA', serviceAccountAuth);

await doc.loadInfo(); // loads document properties and worksheets
await doc.updateProperties({ title: 'renamed doc' });



const sheet = await doc.addSheet({ headerValues: ['name', 'email'] });

// append rows
const larryRow = await sheet.addRow(['new','new@gmail.com']);}
newfunc();
// if creating a new sheet, you can set the header row
